// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoInfo.proto

package com.mgtv.lib.protobuf;

public final class VideoInfo {
  private VideoInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface VideoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mgtv.lib.protobuf.Video)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string clipId = 2;</code>
     * @return The clipId.
     */
    java.lang.String getClipId();
    /**
     * <code>string clipId = 2;</code>
     * @return The bytes for clipId.
     */
    com.google.protobuf.ByteString
        getClipIdBytes();

    /**
     * <code>string clipImage = 3;</code>
     * @return The clipImage.
     */
    java.lang.String getClipImage();
    /**
     * <code>string clipImage = 3;</code>
     * @return The bytes for clipImage.
     */
    com.google.protobuf.ByteString
        getClipImageBytes();

    /**
     * <code>string clipName = 4;</code>
     * @return The clipName.
     */
    java.lang.String getClipName();
    /**
     * <code>string clipName = 4;</code>
     * @return The bytes for clipName.
     */
    com.google.protobuf.ByteString
        getClipNameBytes();

    /**
     * <code>string title = 5;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 5;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     *  repeated AttachInfo attachList = 7;
     * map&lt;string,AttachInfo&gt; attachMap = 8;
     * </pre>
     *
     * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
     * @return Whether the attach field is set.
     */
    boolean hasAttach();
    /**
     * <pre>
     *  repeated AttachInfo attachList = 7;
     * map&lt;string,AttachInfo&gt; attachMap = 8;
     * </pre>
     *
     * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
     * @return The attach.
     */
    com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo getAttach();
  }
  /**
   * Protobuf type {@code com.mgtv.lib.protobuf.Video}
   */
  public  static final class Video extends
      com.google.protobuf.GeneratedMessageLite<
          Video, Video.Builder> implements
      // @@protoc_insertion_point(message_implements:com.mgtv.lib.protobuf.Video)
      VideoOrBuilder {
    private Video() {
      clipId_ = "";
      clipImage_ = "";
      clipName_ = "";
      title_ = "";
    }
    public interface AttachInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.mgtv.lib.protobuf.Video.AttachInfo)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>int32 force = 1;</code>
       * @return The force.
       */
      int getForce();

      /**
       * <code>repeated string displays = 2;</code>
       * @return A list containing the displays.
       */
      java.util.List<java.lang.String>
          getDisplaysList();
      /**
       * <code>repeated string displays = 2;</code>
       * @return The count of displays.
       */
      int getDisplaysCount();
      /**
       * <code>repeated string displays = 2;</code>
       * @param index The index of the element to return.
       * @return The displays at the given index.
       */
      java.lang.String getDisplays(int index);
      /**
       * <code>repeated string displays = 2;</code>
       * @param index The index of the element to return.
       * @return The displays at the given index.
       */
      com.google.protobuf.ByteString
          getDisplaysBytes(int index);
    }
    /**
     * Protobuf type {@code com.mgtv.lib.protobuf.Video.AttachInfo}
     */
    public  static final class AttachInfo extends
        com.google.protobuf.GeneratedMessageLite<
            AttachInfo, AttachInfo.Builder> implements
        // @@protoc_insertion_point(message_implements:com.mgtv.lib.protobuf.Video.AttachInfo)
        AttachInfoOrBuilder {
      private AttachInfo() {
        displays_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      }
      public static final int FORCE_FIELD_NUMBER = 1;
      private int force_;
      /**
       * <code>int32 force = 1;</code>
       * @return The force.
       */
      @java.lang.Override
      public int getForce() {
        return force_;
      }
      /**
       * <code>int32 force = 1;</code>
       * @param value The force to set.
       */
      private void setForce(int value) {
        
        force_ = value;
      }
      /**
       * <code>int32 force = 1;</code>
       */
      private void clearForce() {
        
        force_ = 0;
      }

      public static final int DISPLAYS_FIELD_NUMBER = 2;
      private com.google.protobuf.Internal.ProtobufList<java.lang.String> displays_;
      /**
       * <code>repeated string displays = 2;</code>
       * @return A list containing the displays.
       */
      @java.lang.Override
      public java.util.List<java.lang.String> getDisplaysList() {
        return displays_;
      }
      /**
       * <code>repeated string displays = 2;</code>
       * @return The count of displays.
       */
      @java.lang.Override
      public int getDisplaysCount() {
        return displays_.size();
      }
      /**
       * <code>repeated string displays = 2;</code>
       * @param index The index of the element to return.
       * @return The displays at the given index.
       */
      @java.lang.Override
      public java.lang.String getDisplays(int index) {
        return displays_.get(index);
      }
      /**
       * <code>repeated string displays = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the displays at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDisplaysBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
            displays_.get(index));
      }
      private void ensureDisplaysIsMutable() {
        com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
            displays_;  if (!tmp.isModifiable()) {
          displays_ =
              com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
         }
      }
      /**
       * <code>repeated string displays = 2;</code>
       * @param index The index to set the value at.
       * @param value The displays to set.
       */
      private void setDisplays(
          int index, java.lang.String value) {
        value.getClass();
  ensureDisplaysIsMutable();
        displays_.set(index, value);
      }
      /**
       * <code>repeated string displays = 2;</code>
       * @param value The displays to add.
       */
      private void addDisplays(
          java.lang.String value) {
        value.getClass();
  ensureDisplaysIsMutable();
        displays_.add(value);
      }
      /**
       * <code>repeated string displays = 2;</code>
       * @param values The displays to add.
       */
      private void addAllDisplays(
          java.lang.Iterable<java.lang.String> values) {
        ensureDisplaysIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
            values, displays_);
      }
      /**
       * <code>repeated string displays = 2;</code>
       */
      private void clearDisplays() {
        displays_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      }
      /**
       * <code>repeated string displays = 2;</code>
       * @param value The bytes of the displays to add.
       */
      private void addDisplaysBytes(
          com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensureDisplaysIsMutable();
        displays_.add(value.toStringUtf8());
      }

      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code com.mgtv.lib.protobuf.Video.AttachInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.mgtv.lib.protobuf.Video.AttachInfo)
          com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfoOrBuilder {
        // Construct using com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>int32 force = 1;</code>
         * @return The force.
         */
        @java.lang.Override
        public int getForce() {
          return instance.getForce();
        }
        /**
         * <code>int32 force = 1;</code>
         * @param value The force to set.
         * @return This builder for chaining.
         */
        public Builder setForce(int value) {
          copyOnWrite();
          instance.setForce(value);
          return this;
        }
        /**
         * <code>int32 force = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearForce() {
          copyOnWrite();
          instance.clearForce();
          return this;
        }

        /**
         * <code>repeated string displays = 2;</code>
         * @return A list containing the displays.
         */
        @java.lang.Override
        public java.util.List<java.lang.String>
            getDisplaysList() {
          return java.util.Collections.unmodifiableList(
              instance.getDisplaysList());
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @return The count of displays.
         */
        @java.lang.Override
        public int getDisplaysCount() {
          return instance.getDisplaysCount();
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @param index The index of the element to return.
         * @return The displays at the given index.
         */
        @java.lang.Override
        public java.lang.String getDisplays(int index) {
          return instance.getDisplays(index);
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @param index The index of the value to return.
         * @return The bytes of the displays at the given index.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getDisplaysBytes(int index) {
          return instance.getDisplaysBytes(index);
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @param index The index to set the value at.
         * @param value The displays to set.
         * @return This builder for chaining.
         */
        public Builder setDisplays(
            int index, java.lang.String value) {
          copyOnWrite();
          instance.setDisplays(index, value);
          return this;
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @param value The displays to add.
         * @return This builder for chaining.
         */
        public Builder addDisplays(
            java.lang.String value) {
          copyOnWrite();
          instance.addDisplays(value);
          return this;
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @param values The displays to add.
         * @return This builder for chaining.
         */
        public Builder addAllDisplays(
            java.lang.Iterable<java.lang.String> values) {
          copyOnWrite();
          instance.addAllDisplays(values);
          return this;
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearDisplays() {
          copyOnWrite();
          instance.clearDisplays();
          return this;
        }
        /**
         * <code>repeated string displays = 2;</code>
         * @param value The bytes of the displays to add.
         * @return This builder for chaining.
         */
        public Builder addDisplaysBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.addDisplaysBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.mgtv.lib.protobuf.Video.AttachInfo)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "force_",
                "displays_",
              };
              java.lang.String info =
                  "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0004\u0002\u021a" +
                  "";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo> parser = PARSER;
            if (parser == null) {
              synchronized (com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.mgtv.lib.protobuf.Video.AttachInfo)
      private static final com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo DEFAULT_INSTANCE;
      static {
        AttachInfo defaultInstance = new AttachInfo();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          AttachInfo.class, defaultInstance);
      }

      public static com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<AttachInfo> PARSER;

      public static com.google.protobuf.Parser<AttachInfo> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(long value) {
      
      id_ = value;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0L;
    }

    public static final int CLIPID_FIELD_NUMBER = 2;
    private java.lang.String clipId_;
    /**
     * <code>string clipId = 2;</code>
     * @return The clipId.
     */
    @java.lang.Override
    public java.lang.String getClipId() {
      return clipId_;
    }
    /**
     * <code>string clipId = 2;</code>
     * @return The bytes for clipId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClipIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clipId_);
    }
    /**
     * <code>string clipId = 2;</code>
     * @param value The clipId to set.
     */
    private void setClipId(
        java.lang.String value) {
      value.getClass();
  
      clipId_ = value;
    }
    /**
     * <code>string clipId = 2;</code>
     */
    private void clearClipId() {
      
      clipId_ = getDefaultInstance().getClipId();
    }
    /**
     * <code>string clipId = 2;</code>
     * @param value The bytes for clipId to set.
     */
    private void setClipIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      clipId_ = value.toStringUtf8();
      
    }

    public static final int CLIPIMAGE_FIELD_NUMBER = 3;
    private java.lang.String clipImage_;
    /**
     * <code>string clipImage = 3;</code>
     * @return The clipImage.
     */
    @java.lang.Override
    public java.lang.String getClipImage() {
      return clipImage_;
    }
    /**
     * <code>string clipImage = 3;</code>
     * @return The bytes for clipImage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClipImageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clipImage_);
    }
    /**
     * <code>string clipImage = 3;</code>
     * @param value The clipImage to set.
     */
    private void setClipImage(
        java.lang.String value) {
      value.getClass();
  
      clipImage_ = value;
    }
    /**
     * <code>string clipImage = 3;</code>
     */
    private void clearClipImage() {
      
      clipImage_ = getDefaultInstance().getClipImage();
    }
    /**
     * <code>string clipImage = 3;</code>
     * @param value The bytes for clipImage to set.
     */
    private void setClipImageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      clipImage_ = value.toStringUtf8();
      
    }

    public static final int CLIPNAME_FIELD_NUMBER = 4;
    private java.lang.String clipName_;
    /**
     * <code>string clipName = 4;</code>
     * @return The clipName.
     */
    @java.lang.Override
    public java.lang.String getClipName() {
      return clipName_;
    }
    /**
     * <code>string clipName = 4;</code>
     * @return The bytes for clipName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClipNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clipName_);
    }
    /**
     * <code>string clipName = 4;</code>
     * @param value The clipName to set.
     */
    private void setClipName(
        java.lang.String value) {
      value.getClass();
  
      clipName_ = value;
    }
    /**
     * <code>string clipName = 4;</code>
     */
    private void clearClipName() {
      
      clipName_ = getDefaultInstance().getClipName();
    }
    /**
     * <code>string clipName = 4;</code>
     * @param value The bytes for clipName to set.
     */
    private void setClipNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      clipName_ = value.toStringUtf8();
      
    }

    public static final int TITLE_FIELD_NUMBER = 5;
    private java.lang.String title_;
    /**
     * <code>string title = 5;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <code>string title = 5;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>string title = 5;</code>
     * @param value The title to set.
     */
    private void setTitle(
        java.lang.String value) {
      value.getClass();
  
      title_ = value;
    }
    /**
     * <code>string title = 5;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>string title = 5;</code>
     * @param value The bytes for title to set.
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      title_ = value.toStringUtf8();
      
    }

    public static final int ATTACH_FIELD_NUMBER = 6;
    private com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo attach_;
    /**
     * <pre>
     *  repeated AttachInfo attachList = 7;
     * map&lt;string,AttachInfo&gt; attachMap = 8;
     * </pre>
     *
     * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
     */
    @java.lang.Override
    public boolean hasAttach() {
      return attach_ != null;
    }
    /**
     * <pre>
     *  repeated AttachInfo attachList = 7;
     * map&lt;string,AttachInfo&gt; attachMap = 8;
     * </pre>
     *
     * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
     */
    @java.lang.Override
    public com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo getAttach() {
      return attach_ == null ? com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo.getDefaultInstance() : attach_;
    }
    /**
     * <pre>
     *  repeated AttachInfo attachList = 7;
     * map&lt;string,AttachInfo&gt; attachMap = 8;
     * </pre>
     *
     * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
     */
    private void setAttach(com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo value) {
      value.getClass();
  attach_ = value;
      
      }
    /**
     * <pre>
     *  repeated AttachInfo attachList = 7;
     * map&lt;string,AttachInfo&gt; attachMap = 8;
     * </pre>
     *
     * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeAttach(com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo value) {
      value.getClass();
  if (attach_ != null &&
          attach_ != com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo.getDefaultInstance()) {
        attach_ =
          com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo.newBuilder(attach_).mergeFrom(value).buildPartial();
      } else {
        attach_ = value;
      }
      
    }
    /**
     * <pre>
     *  repeated AttachInfo attachList = 7;
     * map&lt;string,AttachInfo&gt; attachMap = 8;
     * </pre>
     *
     * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
     */
    private void clearAttach() {  attach_ = null;
      
    }

    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mgtv.lib.protobuf.VideoInfo.Video parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.mgtv.lib.protobuf.VideoInfo.Video prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.mgtv.lib.protobuf.Video}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mgtv.lib.protobuf.VideoInfo.Video, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mgtv.lib.protobuf.Video)
        com.mgtv.lib.protobuf.VideoInfo.VideoOrBuilder {
      // Construct using com.mgtv.lib.protobuf.VideoInfo.Video.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return instance.getId();
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string clipId = 2;</code>
       * @return The clipId.
       */
      @java.lang.Override
      public java.lang.String getClipId() {
        return instance.getClipId();
      }
      /**
       * <code>string clipId = 2;</code>
       * @return The bytes for clipId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClipIdBytes() {
        return instance.getClipIdBytes();
      }
      /**
       * <code>string clipId = 2;</code>
       * @param value The clipId to set.
       * @return This builder for chaining.
       */
      public Builder setClipId(
          java.lang.String value) {
        copyOnWrite();
        instance.setClipId(value);
        return this;
      }
      /**
       * <code>string clipId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClipId() {
        copyOnWrite();
        instance.clearClipId();
        return this;
      }
      /**
       * <code>string clipId = 2;</code>
       * @param value The bytes for clipId to set.
       * @return This builder for chaining.
       */
      public Builder setClipIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClipIdBytes(value);
        return this;
      }

      /**
       * <code>string clipImage = 3;</code>
       * @return The clipImage.
       */
      @java.lang.Override
      public java.lang.String getClipImage() {
        return instance.getClipImage();
      }
      /**
       * <code>string clipImage = 3;</code>
       * @return The bytes for clipImage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClipImageBytes() {
        return instance.getClipImageBytes();
      }
      /**
       * <code>string clipImage = 3;</code>
       * @param value The clipImage to set.
       * @return This builder for chaining.
       */
      public Builder setClipImage(
          java.lang.String value) {
        copyOnWrite();
        instance.setClipImage(value);
        return this;
      }
      /**
       * <code>string clipImage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClipImage() {
        copyOnWrite();
        instance.clearClipImage();
        return this;
      }
      /**
       * <code>string clipImage = 3;</code>
       * @param value The bytes for clipImage to set.
       * @return This builder for chaining.
       */
      public Builder setClipImageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClipImageBytes(value);
        return this;
      }

      /**
       * <code>string clipName = 4;</code>
       * @return The clipName.
       */
      @java.lang.Override
      public java.lang.String getClipName() {
        return instance.getClipName();
      }
      /**
       * <code>string clipName = 4;</code>
       * @return The bytes for clipName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClipNameBytes() {
        return instance.getClipNameBytes();
      }
      /**
       * <code>string clipName = 4;</code>
       * @param value The clipName to set.
       * @return This builder for chaining.
       */
      public Builder setClipName(
          java.lang.String value) {
        copyOnWrite();
        instance.setClipName(value);
        return this;
      }
      /**
       * <code>string clipName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClipName() {
        copyOnWrite();
        instance.clearClipName();
        return this;
      }
      /**
       * <code>string clipName = 4;</code>
       * @param value The bytes for clipName to set.
       * @return This builder for chaining.
       */
      public Builder setClipNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClipNameBytes(value);
        return this;
      }

      /**
       * <code>string title = 5;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>string title = 5;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>string title = 5;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>string title = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>string title = 5;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <pre>
       *  repeated AttachInfo attachList = 7;
       * map&lt;string,AttachInfo&gt; attachMap = 8;
       * </pre>
       *
       * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
       */
      @java.lang.Override
      public boolean hasAttach() {
        return instance.hasAttach();
      }
      /**
       * <pre>
       *  repeated AttachInfo attachList = 7;
       * map&lt;string,AttachInfo&gt; attachMap = 8;
       * </pre>
       *
       * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
       */
      @java.lang.Override
      public com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo getAttach() {
        return instance.getAttach();
      }
      /**
       * <pre>
       *  repeated AttachInfo attachList = 7;
       * map&lt;string,AttachInfo&gt; attachMap = 8;
       * </pre>
       *
       * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
       */
      public Builder setAttach(com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo value) {
        copyOnWrite();
        instance.setAttach(value);
        return this;
        }
      /**
       * <pre>
       *  repeated AttachInfo attachList = 7;
       * map&lt;string,AttachInfo&gt; attachMap = 8;
       * </pre>
       *
       * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
       */
      public Builder setAttach(
          com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setAttach(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       *  repeated AttachInfo attachList = 7;
       * map&lt;string,AttachInfo&gt; attachMap = 8;
       * </pre>
       *
       * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
       */
      public Builder mergeAttach(com.mgtv.lib.protobuf.VideoInfo.Video.AttachInfo value) {
        copyOnWrite();
        instance.mergeAttach(value);
        return this;
      }
      /**
       * <pre>
       *  repeated AttachInfo attachList = 7;
       * map&lt;string,AttachInfo&gt; attachMap = 8;
       * </pre>
       *
       * <code>.com.mgtv.lib.protobuf.Video.AttachInfo attach = 6;</code>
       */
      public Builder clearAttach() {  copyOnWrite();
        instance.clearAttach();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mgtv.lib.protobuf.Video)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mgtv.lib.protobuf.VideoInfo.Video();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "clipId_",
              "clipImage_",
              "clipName_",
              "title_",
              "attach_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0002\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.mgtv.lib.protobuf.VideoInfo.Video> parser = PARSER;
          if (parser == null) {
            synchronized (com.mgtv.lib.protobuf.VideoInfo.Video.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.mgtv.lib.protobuf.VideoInfo.Video>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.mgtv.lib.protobuf.Video)
    private static final com.mgtv.lib.protobuf.VideoInfo.Video DEFAULT_INSTANCE;
    static {
      Video defaultInstance = new Video();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Video.class, defaultInstance);
    }

    public static com.mgtv.lib.protobuf.VideoInfo.Video getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Video> PARSER;

    public static com.google.protobuf.Parser<Video> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
