// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoInfoWraper.proto

package com.mgtv.lib.protobuf;

public final class VideoInfoWrapper {
  private VideoInfoWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface VideoWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mgtv.lib.protobuf.VideoWrapper)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    java.util.List<com.mgtv.lib.protobuf.VideoInfo.Video> 
        getVideoList();
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    com.mgtv.lib.protobuf.VideoInfo.Video getVideo(int index);
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    int getVideoCount();
  }
  /**
   * Protobuf type {@code com.mgtv.lib.protobuf.VideoWrapper}
   */
  public  static final class VideoWrapper extends
      com.google.protobuf.GeneratedMessageLite<
          VideoWrapper, VideoWrapper.Builder> implements
      // @@protoc_insertion_point(message_implements:com.mgtv.lib.protobuf.VideoWrapper)
      VideoWrapperOrBuilder {
    private VideoWrapper() {
      video_ = emptyProtobufList();
    }
    public static final int VIDEO_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.mgtv.lib.protobuf.VideoInfo.Video> video_;
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.mgtv.lib.protobuf.VideoInfo.Video> getVideoList() {
      return video_;
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    public java.util.List<? extends com.mgtv.lib.protobuf.VideoInfo.VideoOrBuilder> 
        getVideoOrBuilderList() {
      return video_;
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    @java.lang.Override
    public int getVideoCount() {
      return video_.size();
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    @java.lang.Override
    public com.mgtv.lib.protobuf.VideoInfo.Video getVideo(int index) {
      return video_.get(index);
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    public com.mgtv.lib.protobuf.VideoInfo.VideoOrBuilder getVideoOrBuilder(
        int index) {
      return video_.get(index);
    }
    private void ensureVideoIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.mgtv.lib.protobuf.VideoInfo.Video> tmp = video_;
      if (!tmp.isModifiable()) {
        video_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    private void setVideo(
        int index, com.mgtv.lib.protobuf.VideoInfo.Video value) {
      value.getClass();
  ensureVideoIsMutable();
      video_.set(index, value);
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    private void addVideo(com.mgtv.lib.protobuf.VideoInfo.Video value) {
      value.getClass();
  ensureVideoIsMutable();
      video_.add(value);
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    private void addVideo(
        int index, com.mgtv.lib.protobuf.VideoInfo.Video value) {
      value.getClass();
  ensureVideoIsMutable();
      video_.add(index, value);
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    private void addAllVideo(
        java.lang.Iterable<? extends com.mgtv.lib.protobuf.VideoInfo.Video> values) {
      ensureVideoIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, video_);
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    private void clearVideo() {
      video_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
     */
    private void removeVideo(int index) {
      ensureVideoIsMutable();
      video_.remove(index);
    }

    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.mgtv.lib.protobuf.VideoWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mgtv.lib.protobuf.VideoWrapper)
        com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapperOrBuilder {
      // Construct using com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.mgtv.lib.protobuf.VideoInfo.Video> getVideoList() {
        return java.util.Collections.unmodifiableList(
            instance.getVideoList());
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      @java.lang.Override
      public int getVideoCount() {
        return instance.getVideoCount();
      }/**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      @java.lang.Override
      public com.mgtv.lib.protobuf.VideoInfo.Video getVideo(int index) {
        return instance.getVideo(index);
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder setVideo(
          int index, com.mgtv.lib.protobuf.VideoInfo.Video value) {
        copyOnWrite();
        instance.setVideo(index, value);
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder setVideo(
          int index, com.mgtv.lib.protobuf.VideoInfo.Video.Builder builderForValue) {
        copyOnWrite();
        instance.setVideo(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder addVideo(com.mgtv.lib.protobuf.VideoInfo.Video value) {
        copyOnWrite();
        instance.addVideo(value);
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder addVideo(
          int index, com.mgtv.lib.protobuf.VideoInfo.Video value) {
        copyOnWrite();
        instance.addVideo(index, value);
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder addVideo(
          com.mgtv.lib.protobuf.VideoInfo.Video.Builder builderForValue) {
        copyOnWrite();
        instance.addVideo(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder addVideo(
          int index, com.mgtv.lib.protobuf.VideoInfo.Video.Builder builderForValue) {
        copyOnWrite();
        instance.addVideo(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder addAllVideo(
          java.lang.Iterable<? extends com.mgtv.lib.protobuf.VideoInfo.Video> values) {
        copyOnWrite();
        instance.addAllVideo(values);
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder clearVideo() {
        copyOnWrite();
        instance.clearVideo();
        return this;
      }
      /**
       * <code>repeated .com.mgtv.lib.protobuf.Video video = 1;</code>
       */
      public Builder removeVideo(int index) {
        copyOnWrite();
        instance.removeVideo(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mgtv.lib.protobuf.VideoWrapper)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "video_",
              com.mgtv.lib.protobuf.VideoInfo.Video.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper> parser = PARSER;
          if (parser == null) {
            synchronized (com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.mgtv.lib.protobuf.VideoWrapper)
    private static final com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper DEFAULT_INSTANCE;
    static {
      VideoWrapper defaultInstance = new VideoWrapper();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        VideoWrapper.class, defaultInstance);
    }

    public static com.mgtv.lib.protobuf.VideoInfoWrapper.VideoWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<VideoWrapper> PARSER;

    public static com.google.protobuf.Parser<VideoWrapper> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
